name: Test cpp

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/test-cpp.yaml"
      - "cpp/**"
      - "encoding-core/**"
      - "native-tests/**"
      - "scripts/generate-cpp-dataset.js"
      - "tests-datasets/dataset.json"
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test-cpp:
    name: Run GTest suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0

      - name: Setup JS
        uses: ./.github/actions/setup-js
        with:
          enable-cache: true

      - name: Run GTest
        run: yarn test:cpp:prepare
        shell: bash
